C4Container
    title Backoffice - C4Container
    Container_Boundary(be, "Backoffice") {
        Container(backend_api_v1, "APIv1", "Nodejs", "https")
        Container(backend_api_v3, "APIv3", "Nodejs", "https")
        Container(rsp_api, "RSP", "Nodejs", "https")
        Container(rule_api, "Rule Engine", "Nodejs", "https")
        Container(batch, "Batch", "Pentaho")
        ContainerDb(dbcore, "Core Database", "SQLMI")
        ContainerDb(dbrsp, "RSP Database", "SQLMI")
        ContainerDb(nosql, "MongoDB", "MongoDB", "https")
    }

    Container_Boundary(fe, "Frontoffice") {
        Container(web, "Web", "React", "https")
        Container(app, "App", "React Native", "https")
    }
